print("Hello")
print("well" + "hello")
print("fdfd dfd ".upper())
print("WERT".lower())
print("fdfd dfd".title())
print("fdfd dfd".replace("fd", "ddddeded"))
print("ddf s s sd s s".split())
print("ddf s s sd s s".split("sd"))
print("ddf s s sd s s".split("s"))
print("csaba fgt".capitalize())